[package]
name = "opsynth"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13"
hound = "3.5"
rtrb = "0.2"

[dev-dependencies]
cpal = "0.13"

[[example]]
name = "drone"
crate-type = ["bin"]

[[example]]
name = "sequencer"
crate-type = ["bin"]
